### PR TITLE
Added the header feature

### PR DESCRIPTION
**Pull request by salawekesa**
<h1>Header feat</h1>
<p>Created the header element and added a logo, navigation menu and two access buttons<p>

### CODE REVIEW

**Comment by jumalaw98** [comment]
Fix up the conflicts, then remember to assign yourself an issue before working on it

**Comment by salawekesa** [comment]
Pardon me, its my first time contributing i hope i get it right next time

**Comment by jumalaw98** [comment]
Can we have a chat, or a whatsapp call whatsapp?

**Comment by jumalaw98** [comment]
Your feature had conflict with other pr, that was done by someone.
Hope you managed to know why.

**Pull request closed without merging**
