### PR TITLE
Created forgot password-002 #12

### PR DESCRIPTION
**Pull request by salawekesa**

### CODE REVIEW

**Review by jumalaw98 — CHANGES_REQUESTED** [review]
Good work done, but your didnt follow the project structure,
Restructure the code, then amend the branch with new updates

**Comment by salawekesa** [comment]
Okay let me work on the changes

**Review by salawekesa — COMMENTED** [review]
restructured the code

**Comment by the-odyssey-21** [comment]
> restructured the code

Done

**Comment by salawekesa** [comment]
> restructured the code

Done

**Review by jumalaw98 — APPROVED** [review]

**Pull request merged**
